FROM php:8-fpm

RUN apt-get update && \
  apt-get install -y libfreetype6-dev libjpeg-dev libpng-dev && \
  docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
  docker-php-ext-install gd && \
  apt-get install -y mariadb-client

RUN docker-php-ext-install opcache
RUN docker-php-ext-install pdo_mysql
