#!/usr/bin/env python

import plotly
from plotly.graph_objs import Scatter, Layout, Figure
import json
import sys

"""
Args:
  1. file path (must end with .html)
"""

file_path = sys.argv[1]

pairs = [json.loads("[" + line.strip() + "]") for line in sys.stdin]
x_pos = [pair[0] for pair in pairs]
y_pos = [pair[1] for pair in pairs]

trace1 = Scatter(
    x=x_pos,
    y=y_pos,
    name='Values'
)

data = [trace1]

layout = Layout(
    showlegend=True,
    title="Total: " + str(sum(y_pos))
)

fig = Figure(data=data, layout=layout)

plotly.offline.plot(fig, auto_open=False, filename=file_path)